### PR TITLE
Improve gif quality by appropriately sizing gifs

### PR DESCRIPTION
**Pull request by jkupferman**
The existing code resized gifs down to 320x240 which twitter then scaled back up to 528x396 resulting in grainy gifs. This change r
It also tells gifsicle to limit gif colors to 256 which should reduce file size.

NOTE: This code should be tested to ensure that it generates gifs below the 3MB Twitter limit.

### CODE REVIEW

**Comment by jkupferman** [comment]
While I think this will help with overall quality and size, I suspect you'd get much better results by posting an reasonably sized mp4 to twitter (as a video). You'd be able to achieve much higher video quality and stay well below the twitter video size limit.

**Comment by xdamman** [comment]
Thanks for this, really appreciate the contribution here. Let me test this first.

I also tweet the link to the mp4. Twitter doesn't let you upload a mp4 unfortunately. The only solution is to have my own player but they would first need to approve it.

**Comment by xdamman** [comment]
Works great, merging! Thanks again!

**Comment by FredericJacobs** [comment]
Or reverse the Vine/Instagram API? 0:)

**Pull request merged**
